#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title CommuniGate online users'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel users'
    echo 'graph_category CommuniGate'
    echo 'imap.label IMAP'
    echo 'imap.type GAUGE'
    echo 'imap.min 0'
    echo 'imap.draw AREA'
    echo 'http.label HTTP'
    echo 'http.type GAUGE'
    echo 'http.min 0'
    echo 'http.draw STACK'
    echo 'pop.label POP'
    echo 'pop.type GAUGE'
    echo 'pop.min 0'
    echo 'pop.draw STACK'
    exit 0
fi

echo -n "imap.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.4.2.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "http.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.5.2.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "pop.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.3.2.0 2>/dev/null | cut -d " " -f 2) || echo U