#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title CommuniGate mail throughput'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel messages'
    echo 'graph_category CommuniGate'
    echo 'received.label received'
    echo 'received.type DERIVE'
    echo 'received.min 0'
    echo 'received.draw AREA'
    echo 'sent.label sent'
    echo 'sent.type DERIVE'
    echo 'sent.min 0'
    echo 'sent.draw STACK'
    echo 'delivered.label delivered'
    echo 'delivered.type DERIVE'
    echo 'delivered.min 0'
    echo 'delivered.draw LINE2'
    exit 0
fi

echo -n "received.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.1.1.10.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "sent.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.1.2.10.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "delivered.value "
(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.6.10.0 2>/dev/null | cut -d " " -f 2) || echo U