#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title CPU'
    echo 'graph_args -l 0 -u 100 -r --base 1000'
    echo 'graph_vlabel CPU'
    echo 'graph_category BlueCoat'


    echo 'cpu.label CPU'
    echo 'cpu.type GAUGE'
    echo 'cpu.min 0'
    echo 'cpu.draw LINE2'
    
    exit 0
fi

echo -n "cpu.value "
(snmpget -v 2c -c public -O v 10.0.0.111 1.3.6.1.4.1.3417.2.11.2.4.1.8.1 2>/dev/null | cut -d " " -f 2) || echo U

