#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Netapp 2040_1 CPU'
    echo 'graph_args -l 0 -u 100 -r --base 1000'
    echo 'graph_vlabel CPU'
    echo 'graph_category Netapp_2040_1'


#    echo 'cpu.label CPU Netapp 2020'
#    echo 'cpu.type GAUGE'
#    echo 'cpu.min 0'
#    echo 'cpu.max 100'
#    echo 'cpu.draw LINE2'
#    echo 'cpuCPInterruptPercent.label cpuCPInterrupt Netapp 2020'
#    echo 'cpuCPInterruptPercent.type GAUGE'
#    echo 'cpuCPInterruptPercent.min 0'
#    echo 'cpuCPInterruptPercent.draw LINE2'
#    echo 'cpuNonCPInterruptPercent.label cpuNonCPInterrupt Netapp 2020'
#    echo 'cpuNonCPInterruptPercent.type GAUGE'
#    echo 'cpuNonCPInterruptPercent.min 0'
#    echo 'cpuNonCPInterruptPercent.draw LINE2'
    
    echo 'cpu1.label CPU Netapp 2040_1'
    echo 'cpu1.type GAUGE'
    echo 'cpu1.min 0'
#    echo 'cpu1.max 100'
    echo 'cpu1.draw LINE2'
    echo 'cpuCPInterruptPercent1.label cpuCPInterrupt Netapp 2040_1'
    echo 'cpuCPInterruptPercent1.type GAUGE'
    echo 'cpuCPInterruptPercent1.min 0'
    echo 'cpuCPInterruptPercent1.draw LINE2'
    echo 'cpuNonCPInterruptPercent1.label cpuNonCPInterrupt Netapp 2040_1'
    echo 'cpuNonCPInterruptPercent1.type GAUGE'
    echo 'cpuNonCPInterruptPercent1.min 0'
    echo 'cpuNonCPInterruptPercent1.draw LINE2'

#    echo 'cpu2.label CPU Netapp 2040_2'
#    echo 'cpu2.type GAUGE'
#    echo 'cpu2.min 0'
#    echo 'cpu2.max 100'
#    echo 'cpu2.draw LINE2'
#    echo 'cpuCPInterruptPercent2.label cpuCPInterrupt Netapp 2040_2'
#    echo 'cpuCPInterruptPercent2.type GAUGE'
#    echo 'cpuCPInterruptPercent2.min 0'
#    echo 'cpuCPInterruptPercent2.draw LINE2'
#    echo 'cpuNonCPInterruptPercent2.label cpuNonCPInterrupt Netapp 2040_2'
#    echo 'cpuNonCPInterruptPercent2.type GAUGE'
#    echo 'cpuNonCPInterruptPercent2.min 0'
#    echo 'cpuNonCPInterruptPercent2.draw LINE2'

    
    exit 0
fi

#echo -n "cpu.value "
#(snmpget -v 2c -c public -O v 10.0.0.31 1.3.6.1.4.1.789.1.2.1.3.0 2>/dev/null | cut -d " " -f 2) || echo U
#echo -n "cpuNonCPInterruptPercent.value "
#(snmpget -v 2c -c public -O v 10.0.0.31 1.3.6.1.4.1.789.1.2.1.12.0 2>/dev/null | cut -d " " -f 2) || echo U
#echo -n "cpuCPInterruptPercent.value "
#(snmpget -v 2c -c public -O v 10.0.0.31 1.3.6.1.4.1.789.1.2.1.11.0 2>/dev/null | cut -d " " -f 2) || echo U

echo -n "cpu1.value "
(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.1.3.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "cpuNonCPInterruptPercent1.value "
(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.1.12.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "cpuCPInterruptPercent1.value "
(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.1.11.0 2>/dev/null | cut -d " " -f 2) || echo U


#echo -n "cpu2.value "
#(snmpget -v 2c -c public -O v 10.0.0.55 1.3.6.1.4.1.789.1.2.1.3.0 2>/dev/null | cut -d " " -f 2) || echo U
#echo -n "cpuNonCPInterruptPercent2.value "
#(snmpget -v 2c -c public -O v 10.0.0.55 1.3.6.1.4.1.789.1.2.1.12.0 2>/dev/null | cut -d " " -f 2) || echo U
#echo -n "cpuCPInterruptPercent2.value "
#(snmpget -v 2c -c public -O v 10.0.0.55 1.3.6.1.4.1.789.1.2.1.11.0 2>/dev/null | cut -d " " -f 2) || echo U

