#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Netapp 2040_1 Ops'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel Ops'
    echo 'graph_category Netapp_2040_1'
#    echo 'imap.label IMAP'
#    echo 'imap.type GAUGE'
#    echo 'imap.min 0'
#    echo 'imap.draw AREA'
    echo 'miscLowCifsOps.label miscLowCifsOps'
    echo 'miscLowCifsOps.type DERIVE'
    echo 'miscLowCifsOps.min 0'
    echo 'miscLowCifsOps.draw LINE2'

#    echo 'miscNfsOps.label miscNfsOps'
#    echo 'miscNfsOps.type DERIVE'
#    echo 'miscNfsOps.min 0'
#    echo 'miscNfsOps.draw LINE2'

    echo 'miscLowNfsOps.label miscLowNfsOps'
    echo 'miscLowNfsOps.type DERIVE'
    echo 'miscLowNfsOps.min 0'
    echo 'miscLowNfsOps.draw LINE2'

    exit 0
fi

#echo -n "miscNfsOps.value "
#(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.2.1.0  2>/dev/null | cut -d " " -f 2) || echo U

echo -n "miscLowNfsOps.value "
(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.2.6.0  2>/dev/null | cut -d " " -f 2) || echo U

echo -n "miscLowCifsOps.value "
(snmpget -v 2c -c public -O v 10.0.0.51 1.3.6.1.4.1.789.1.2.2.8.0 2>/dev/null | cut -d " " -f 2) || echo U


