#!/bin/sh
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Netapp 2240_1 NET_all'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel Kb'
    echo 'graph_category Netapp_2240_1'
#    echo 'imap.label IMAP'
#    echo 'imap.type GAUGE'
#    echo 'imap.min 0'
#    echo 'imap.draw AREA'
    echo 'netsent.label NetSent'
    echo 'netsent.type DERIVE'
    echo 'netsent.min 0'
    echo 'netsent.draw LINE2'
    echo 'netrcvd.label NetRcvd'
    echo 'netrcvd.type DERIVE'
    echo 'netrcvd.min 0'
#    echo 'cpu.max 100'
    echo 'netrcvd.draw LINE2'
    exit 0
fi

#echo -n "imap.value "
#(snmpget -v 1 -c public -O v localhost 1.3.6.1.4.1.5678.2.1.1.4.2.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "netsent.value "
(snmpget -v 2c -c public -O v 10.0.0.80 1.3.6.1.4.1.789.1.2.2.31.0 2>/dev/null | cut -d " " -f 2) || echo U
echo -n "netrcvd.value "
(snmpget -v 2c -c public -O v 10.0.0.80 1.3.6.1.4.1.789.1.2.2.30.0 2>/dev/null | cut -d " " -f 2) || echo U


